/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.List;

import org.example.springjpa.model.User;
import org.example.springjpa.service.UserService;
import org.example.test1.Car;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.support.ClassPathXmlApplicationContext;


public class App {

    private final static Logger logger = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void springOnlyJpa() {
        ApplicationContext context = new AnnotationConfigApplicationContext(org.example.springjpa.AppConfig.class);
        UserService userService = context.getBean(UserService.class);

        logger.info("Adding users...");
        List<User> newUsers = new ArrayList<>();
        newUsers.add(new User("Alice", 34));
        newUsers.add(new User("Bob", 24));
        newUsers.add(new User("Key", 56));

        List<User> addedUsers = new ArrayList<>();

        for(User user : newUsers) {
            addedUsers.add(userService.saveUser(user));
        }

        List<User> users = userService.getAllUsers();
        for (User user : users) {
            System.out.println(user);
        }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // ApplicationContext context = new AnnotationConfigApplicationContext(Config.class);
        // ApplicationContext context = new ClassPathXmlApplicationContext("beans.xml");
        // Employee emp = (Employee) context.getBean("emp1");
        // System.out.println(emp);

        // String[] beanNames = context.getBeanDefinitionNames();
        // for (String beanName : beanNames) {
        //     System.out.println(beanName);
        // }

        // for (String beanName : beanNames) {
        //     Object bean = context.getBean(beanName);
        //     if (bean instanceof Car) {
        //         ((Car) bean).drive();
        //     }
        // }

        // org.example.test2.Car car = context.getBean(org.example.test2.Car.class);
        // car.run();
        springOnlyJpa();
    }
}
